# Save this content to a file like dockerhub-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: mixit
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYWZmdWw3IiwicGFzc3dvcmQiOiJBb3V0MTAsMjAwNCIsImVtYWlsIjoibWFydGluYWZmdWwwNzBAZ21haWwuY29tIiwiYXV0aCI6ImJXRm1ablZzTnpwQmIzVjBNVEFzTWpBd05BPT0ifX19