# This is a template for creating the necessary Kubernetes secrets
# Replace the placeholder values with actual values before applying
# to DO NOT commit this file with actual secrets to version control

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mixit
type: Opaque
stringData:
  uri: mongodb+srv://martinafful:group74pass@clusterrecipe.efjgncy.mongodb.net
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-secret
  namespace: mixit
type: Opaque
stringData:
  cloud-name: dvkfxnpqp
  api-key: "214428539681575"
  api-secret: KK-gqWmyTk4hJxCcod2FY80WKHY
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: mixit
type: Opaque
stringData:
  secret: ASDFGHJKLQWERTYUIOPZXCVBNM1234567890qwertyuiopasdfghjklzxcvbnm1234567890asdfghjklqwertyuiopasdfghjkl
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: mixit
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYWZmdWw3IiwicGFzc3dvcmQiOiJBb3V0MTAsMjAwNCIsImVtYWlsIjoibWFydGluYWZmdWwwNzBAZ21haWwuY29tIiwiYXV0aCI6ImJXRm1ablZzTnpwQmIzVjBNVEFzTWpBd05BPT0ifX19


# Note: The .dockerconfigjson value above is a placeholder
# Generate the actual value with:
# kubectl create secret docker-registry dockerhub-secret --docker-server=https://index.docker.io/v1/ --docker-username=your-username --docker-password=your-password --docker-email=your-email@example.com --dry-run=client -o yaml

